### ISSUE TITLE
Error in if (fam.path) { : argument is not interpretable as logical

### ISSUE THREAD

**Issue by angelesdecara** [andrewparkermorgan/popcorn#1]
Hi,
I'm trying to make a pretty admixture plot, so far unsuccessfully...

I get these two errors:

> pops=read_fam("../all663pruned0.82.fam")
> Q=read_Q_matrix("all663pruned0.82.3.Q")
Reading ancestry proportions from <all663pruned0.82.3.Q>...
Parsed with column specification:
cols(
  X1 = col_double(),
  X2 = col_double(),
  X3 = col_double()
)
Error in if (fam.path) { : argument is not interpretable as logical

and then

QQ <- tidy(Q, pops)
Error in tidy(Q, pops) : could not find function "tidy"

Many thanks for your help!

**Comment by andrewparkermorgan** [comment]
I have just pushed an update that should make the generic function `tidy()` discoverable, and addresses the problem with the `fam.path` argument. Thanks for your interest in `popcorn`.
