### ISSUE TITLE
barplot color

### ISSUE THREAD

**Issue by Sh1ne111** [andrewparkermorgan/popcorn#2]
Hi,
   how to customize the color of Barplot in the function? I did not find the relevant parameters. thanks!

chens

**Comment by andrewparkermorgan** [comment]
Which plotting function are you trying to use? There is no `barplot()` in `popcorn`. However, I can tell you that most of the plotting functions in `popcorn` return a `ggplot` object, so you should be able to use any of the discrete color scales in `ggplot2` to get the result you want. It would help if you can provide a snippet of the code you're trying to use.

**Comment by Sh1ne111** [comment]
I want to use plot_admixture to plot Q matrix, but I can't customize the
group color.

code:
library(popcorn)
library(ggplot2)

pops <- read_fam("test.fam")
Q <- read_Q_matrix("test.3.Q")
so <- sort_by_cluster(Q)
QQ <- tidy(Q, pops)

p<-plot_admixture(QQ, label = TRUE, sort.order = so)

ggsave(p,filename="test.pdf",width=10,height=3)

Andrew Parker Morgan <notifications@github.com> 于2020年8月13日周四 上午11:14写道：

**Comment by andrewparkermorgan** [comment]
The object `p` in your code is a `ggplot` object, so you can just change
the fill colors for the bars with a discrete color scale as you would with
any other plot. For example:

```
library(popcorn)
library(ggplot2)

p <- plot_admixture(QQ, label = TRUE, sort.order = so)
p + scale_fill_brewer(palette = "Set1")
```

**Comment by Sh1ne111** [comment]
thanks for your reply!
